### ISSUE TITLE
How do I add command line option '-G'

### ISSUE THREAD

**Issue by dinki** [LinuxChristian/rtl_433-docker#1]
I'm wanting to use some protocols that disabled by default.  I need to issue the '-G' command line option.  Is this possible with this docker container?  Thanks

**Comment by LinuxChristian** [comment]
Hi dinki,

Sure you can modify line 26 in the rtl_433_events.py file. Currently it looks like this

```
config = {
        'host': os.getenv('MQTT_IP', '127.0.0.1'),
        'port':int(os.getenv('MQTT_PORT', 1883)),
        'auth':os.getenv('MQTT_AUTH', None),
        'command': ['/usr/local/bin/rtl_433', '-F', 'json'] + ['-R {}'.format(d) for d in rtl_devices] + ['-l {}'.format(level)],
        'debug': os.getenv('MQTT_DEBUG', True),
}
```

But I guess you would like this,

```
config = {
        'host': os.getenv('MQTT_IP', '127.0.0.1'),
        'port':int(os.getenv('MQTT_PORT', 1883)),
        'auth':os.getenv('MQTT_AUTH', None),
        'command': ['/usr/local/bin/rtl_433', '-F', 'json'] + ['-G'] + ['-l {}'.format(level)],
        'debug': os.getenv('MQTT_DEBUG', True),
}
```

**Comment by dinki** [comment]
Thank you for this.  I've made the modification.  I'm not seeing any traffic going to my MQTT server from rtl_433  .. Can I trouble you to tell me where I might see the debug output or some sort of log?

**Comment by LinuxChristian** [comment]
Hmmm.. did you remember to build the container after making the changes?

**Comment by LinuxChristian** [comment]
The container should print the command it uses when it starts. I guess you can see it using docker logs or something similar?

**Comment by dinki** [comment]
Yes.. I did rebuild.  I am not getting any output to my MQTT server so I'm wondering if the docker image logs or somehow shows some output so I can see where the problem might lie.  I did not get output before the change either.

**Comment by LinuxChristian** [comment]
Here is the output I get with the standard image using docker run (without the -d),

![screenshot 2018-12-05 at 8 18 54 pm](https://user-images.githubusercontent.com/3591721/49538222-353c6480-f8cb-11e8-9ea8-4e8493f7a75f.png)

That is not what you see?

**Comment by dinki** [comment]
Ahh okay.. I'm still pretty new to docker.  I removed the -d option and after a few seconds I started seeing a ton of these:

WARNING: Received non-json data from rtl_433:                                                                                                                 
WARNING: Received non-json data from rtl_433:                                                                                                                 
WARNING: Received non-json data from rtl_433:                                                                                                                 
WARNING: Received non-json data from rtl_433:                                                                                                                 
WARNING: Received non-json data from rtl_433:                                                                                                                 
WARNING: Received non-json data from rtl_433:                                                                                                                 
WARNING: Received non-json data from rtl_433:

**Comment by dinki** [comment]
This is what it says right before that:

root@omv:~# docker run --name rtl_433 --device=/dev/bus/usb/002/030 -e MQTT_IP='192.168.0.25' --restart=always rtl_433                                        
{'auth': None, 'host': '192.168.0.25', 'debug': True, 'port': 1883, 'command': ['/usr/local/bin/rtl_433', '-F', 'json', '-G', '-l 0']}                        
INFO: Starting command: ['/usr/local/bin/rtl_433', '-F', 'json', '-G', '-l 0']

**Comment by LinuxChristian** [comment]
I see.. That is strange.. I did the same thing and everything worked.
It could be the rtl dongle is registered on the wrong USB port?
But to debug it you perhaps needs to access the container directly and see what is going on. In the docker file change line 18 from

`
CMD python3 rtl_433_events.py
`

to,

`
CMD top
`

This should keep the container running. Then follow this guide to get access to the internals of the container, https://askubuntu.com/questions/505506/how-to-get-bash-or-ssh-into-a-running-container-in-background-mode

From their you should be able to modify the python script and debug the problem a bit more..

As an alternative you can also edit after line 64 in rtl_433_event.py and add a `print(event)` to get some information about what your dongle is returning.

**Comment by dinki** [comment]
I gave it another shot this weekend and got it working.  I'm not sure what the problem was but I ended up having to reboot my server for other reasons and when I reinserted the dongle lsusb showed different information.  I used the new values and suddenly it was working.  Thanks for the help on this.

**Comment by LinuxChristian** [comment]
Great to hear! Then I will close the issue.
