### ISSUE TITLE
The container dies after approximately 20 minutes and stops publishing values. Restarting fixes it.

### ISSUE THREAD

**Issue by nicxvan** [LinuxChristian/rtl_433-docker#4]
Is there a way to provide a healthcheck for this?

**Comment by LinuxChristian** [comment]
Hi @nicxvan, I am really sorry for not seeing your issue before almost a year after you opened it. For some reason, Github doesn't inform me of new issues. Think I have to look through my notification settings :thinking: 

Did you manage to solve the problem?

You can configure a MQTT server to send keep-alive pings to ensure a connection is stable. https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901045

Off the top of my head, that would be the easiest way to react if the publisher stops. When that is said, I shouldn't really stop sending. So just restarting the service is perhaps not the best fix.

**Comment by nlighteneddesign** [comment]
It's working again, I think it actually broke because of an upstream change to rtl_433 it started working again after maybe 2 months. I wrote a healthcheck so that it restarts the container when the 433 process dies.
If I get time I'll do a fork.

I added this to the Dockerfile:
```
COPY healthcheck.py .
HEALTHCHECK --start-period=30s CMD /usr/bin/python3 /tmp/healthcheck.py
```

This is the healthcheck file
```
#!/usr/bin/python3
# -*- coding: utf-8 -*-

import json
from datetime import datetime

f=open("last.txt", "r")
contents =f.read()

last = json.loads(contents)
lastdate = last['time']

timecheck = datetime.now()

lastdateobject = datetime.strptime(lastdate, "%Y-%m-%d %H:%M:%S.%f")

difference = timecheck - lastdateobject
print(int(difference.total_seconds()))

if int(difference.total_seconds()) < 300:
    print(0)
else:
    print(1)
```

Then in events I added 
```
        f= open("/tmp/last.txt","w+")
        f.write(json.dumps(event))
        f.close()
```

**Comment by LinuxChristian** [comment]
Thanks for sharing @nlighteneddesign. I am going to close this again. @nicxvan, please reopen if you are still having problem.
